// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ttrjbslwfdqwakloevzs.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InR0cmpic2x3ZmRxd2FrbG9ldnpzIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTM5NjE4OTMsImV4cCI6MjA2OTUzNzg5M30.FUSzntw9L3VTOjdI6QUwdDvp6ahiXfE531ts6_Zipj0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});